# Generated by Django 3.1.1 on 2021-09-10 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=60, null=True)),
                ('description', models.TextField(blank=True, default='', max_length=200000, null=True)),
                ('industry', models.TextField(blank=True, default='', max_length=20000, null=True)),
                ('phone', models.IntegerField(blank=True, default=999999999, null=True)),
            ],
        ),
    ]
