# Generated by Django 3.1.1 on 2021-09-10 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(blank=True, max_length=60, null=True)),
                ('last_name', models.TextField(blank=True, default='', max_length=200000, null=True)),
                ('fax', models.TextField(blank=True, default='', max_length=20000, null=True)),
                ('phone', models.TextField(blank=True, default='999-999-999', max_length=20000, null=True)),
                ('email', models.TextField(max_length=60, verbose_name='email')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=60, unique=True, verbose_name='username')),
                ('email', models.TextField(max_length=60, verbose_name='email')),
                ('name', models.TextField(blank=True, max_length=60, null=True, verbose_name='name')),
                ('company', models.TextField(blank=True, max_length=200, null=True)),
                ('country', models.TextField(blank=True, default='', max_length=20000, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.TextField(blank=True, default='999-999-999', max_length=20000, null=True),
        ),
    ]
