# Generated by Django 3.1.1 on 2021-09-10 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210910_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.TextField(blank=True, max_length=60, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.TextField(blank=True, max_length=60, null=True, verbose_name='email'),
        ),
    ]
